gitSafeReplacementChar: '-'
branchName: '${assignee.login}/issue-${issue.number}-${issue.title,}'
branches:
  - label: enhancement
    prefix: feature/
    name: 3.x
  - label: bug
    prefix: bugfix/
    name: 3.x
