name: Project automations
on:
  issues:
    types:
      - opened
      - reopened

# map fields with customized labels
env:
  nostatus: 'No Status'

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.nostatus }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.DRUPAL_PROJECT}}
          #user: wrg20
          organization: web-illinois
          project_id: 5
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.nostatus }} # Target status
